sudo: false
language: ruby
rvm:
- 2.5.1
services:
- postgresql
env:
- TZ=America/New_York
before_install:
- gem update --system
- gem install bundler
- echo $TRAVIS_TAG
before_script:
- psql -c "create role manifold with createdb login password 'password';" -U postgres
- RAILS_ENV=test bundle exec rake db:setup
- RAILS_ENV=test bundle exec rake db:seed
- nvm install node
- npm install -g ajv
- npm install -g ajv-cli
script:
- bundle exec rubocop
- bundle exec brakeman
- bundle exec rspec spec
after_success:
- true
before_deploy:
- rm -fR $PYENV_ROOT
- curl https://pyenv.run | bash
- pyenv install -v 3.6.6
- pyenv local 3.6.6
- pip install pipenv
- pipenv install
- openssl aes-256-cbc -K $encrypted_9e51133e104b_key -iv $encrypted_9e51133e104b_iv
  -in .travis/deploy.zip.enc -out .travis/deploy.zip -d
- unzip .travis/deploy.zip -d .travis
- mv .travis/.gritty_travis ~/.ssh/.gritty_travis
- mv .travis/.conan_the_deployer ~/.ssh/.conan_the_deployer
- eval "$(ssh-agent -s)"
- chmod 600 ~/.ssh/.gritty_travis
- chmod 600 ~/.ssh/.conan_the_deployer
- echo -e "Host $BASTION_HOST\n\tStrictHostKeyChecking no\n\tIdentityFile ~/.ssh/.conan_the_deployer\n"
  >> ~/.ssh/config
- echo -e "HOST gitserv\n\tHostname remote.server.com\n\tIdentityFile ~/.ssh/.gritty_travis\n\tIdentitiesOnly
  yes\n" >> ~/.ssh/config
- echo -e "HOST github.com\n\tIdentityFile ~/.ssh/.gritty_travis\n" >> ~/.ssh/config
- ssh-add ~/.ssh/.gritty_travis
- ssh-add ~/.ssh/.conan_the_deployer
deploy:
- provider: script
  script: bash .travis/deploy-qa.sh
  on:
    branch: qa
- provider: script
  script: bash .travis/deploy-stage.sh
  on:
    branch: master
- provider: script
  script: bash .travis/deploy-prod.sh
  on:
    tags: true
    all_branches: true
    condition: "TRAVIS_TAG =~ ^v[0-9]*"
notifications:
  slack:
    secure: m4+n2xKbvGvmEUrAEqV0VjQ6MuGPpfsc1UnQ6pKhdKCW4pN4bvCKEUS339INaUQAeRAQONXShEs1TuTSu1ouJAerIqcF60Q6+Mf8d2sE/0xqLeRJ/W7GX2wK2RO/nDXHxMKQ0GN3WDmOdn8/lXE5M5LugFg4ZN7kGqAKeTE4kmUFIXC9s/OyDHOFRRJRn59HTaFep3mWhLdSJ1iX3jCIn5vkuCdoHSYcIcKupf8RSqVcaa+QngpUzXJxRGRm2BXVtEDx0qCm4M3WdBgbPF37Z6gv9IaGHWJo8zLJnpoU5Bz1rfME1EyhOYHKSP/4nE9YGwHbD6Q7NpGA6Ju6IC4GIweB3W8nb0z64jga2iK7QIob9lFCmb4Yf+rbGiI8suYRm+hNksv5t6L2P4QeXqo7FbQG9BapNAYHpTkUt8ItaDthEOOGT8HY4TYH1JE3buOUzh1i1f2l21zw9bzROe0IzGg0H6UQkI97M4bP9Dt4zteNjsDjISh1N/bKL1WJegjDfhvJxGZCjK773Bkn5c8ZsOwekx1j99XsUWGjVJGWYhMcqanv2dgYhuZoe/Ftzf4e3b0nvMwKmDBtHISQwS4B1rkTVE/emUAqbhxscPtWTgONzPIlA+NVT4ghmDGVcAbokVVjmAq3isOt0t+zVSBn7+D+YLQvfp5x+6/quiP/JjA=
