
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("MANIFOLD_DB_HOST") { "127.0.0.1" } %>
  pool: 5
  username: <%= ENV.fetch("MANIFOLD_DB_USER") { "manifold" } %>
  password: <%= ENV.fetch("MANIFOLD_DB_PASSWORD") { "password" }%>

development:
  <<: *default
  database: manifold_development

test:
  <<: *default
  database: manifold_test

production:
  <<: *default
  database: manifold
